---

- name: Playbool 1
  hosts: web
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Start and Enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enable: true