#Variables from Play
---
- name: variables from play
  hosts: localhost
  vars:
    - myVar: "PLAY"
  tasks:
    - name: play1 task1
      ansible.builtin.debug:
        msg: "I am coming from {{myVar}}""
