#Variables from Prompt
---
- name: variables from play
  hosts: localhost
  vars_prompt:
    - name: myVar
      prompt: "Enter myVar"
      private: false
    - name: msg
      prompt: Enter msg
      private: false

  tasks:
    - name: play1 task1
      ansible.builtin.debug:
        msg: "I am coming from {{myVar}}, {{msg}}"