#Variables from files
---
- name: variables from play
  hosts: localhost
  vars_files:
    - variablefile.yaml
  tasks:
    - name: play1 task1
      ansible.builtin.debug:
        msg: "I am coming from {{myVar}}, {{msg}}"