#Variables from Play
---
- name: variables from play
  hosts: localhost
  # vars:
  #   myVar: "PLAY"
  #   msg: "Hello from PLAY variables"
  # vars_prompt:
  #   - name: myVar
  #     prompt: Enter myVar
  #     private: false
  #   - name: msg
  #     prompt: Enter msg
  #     private: false
  # vars_files:
  #   - variablefile.yaml
  tasks:
    - name: play1 task1
      # vars:
      #   myVar: Task
      #   msg: I am from TAsk
      ansible.builtin.debug:
        msg: "I am coming from {{myVar}}, {{msg}}"

#1. CMD
#2. Task
#3. File
#4. prompt
#5. Play
#6. Inventory
#7. Roles

