---

- name: play1-conditions
  hosts: localhost
  tasks:
    - name: check user
      ansible.builtin.command: id roboshop
      register: myUser
      ignore_errors: true
    - name: print myUser
      ansible.builtin.debug:
        msg: "User details: {{myUser}}"
    - name: create user
      ansible.builtin.user:
        Name: roboshop
      when: myUser.rc != 0
