- name: loops-play
  hosts: localhost
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - git
        - mysql
        - httpd
        - postfix