- name: loops-play
  hosts: localhost
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: {{item.name}}
        state: {{item.state}}
      loop:
        - { name: git, state: present }
        - { name: mysql, state: present }
        - { name: postfix, state: absent }
        - { name: httpd, state: absent }