- name: practicing ansible vault
  hosts: ubuntu-grp
  become: yes
  vars_files:
    - variablefileEncrypted.yaml
  tasks:
    - name: printing vault file variables
      ansible.builtin.debug:
        msg: "{{myVar}}, {{msg}}, {{message}}"